helm: Use fetch depth 0 to fix chart lint problem
Otherwise, it prints the following error due to a shallow clone:

Error: Error linting charts: Error identifying charts to process:
Error running process: exit status 128
No chart changes detected.